// This is the core library of Cloud Development Kit (CDK) for Kubernetes (cdk8s). cdk8s apps synthesize into standard Kubernetes manifests which can be applied to any Kubernetes cluster.
package cdk8s

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdk8s-team/cdk8s-core-go/cdk8s/jsii"

	"github.com/aws/constructs-go/constructs/v3"
	"github.com/cdk8s-team/cdk8s-core-go/cdk8s/internal"
)

type ApiObject interface {
	constructs.Construct
	// The group portion of the API version (e.g. `authorization.k8s.io`).
	ApiGroup() *string
	// The object's API version (e.g. `authorization.k8s.io/v1`).
	ApiVersion() *string
	// The chart in which this object is defined.
	Chart() Chart
	// The object kind.
	Kind() *string
	// Metadata associated with this API object.
	Metadata() ApiObjectMetadataDefinition
	// The name of the API object.
	//
	// If a name is specified in `metadata.name` this will be the name returned.
	// Otherwise, a name will be generated by calling
	// `Chart.of(this).generatedObjectName(this)`, which by default uses the
	// construct path to generate a DNS-compatible name for the resource.
	Name() *string
	// Create a dependency between this ApiObject and other constructs.
	//
	// These can be other ApiObjects, Charts, or custom.
	AddDependency(dependencies ...constructs.IConstruct)
	// Applies a set of RFC-6902 JSON-Patch operations to the manifest synthesized for this API object.
	//
	// Example:
	//     kubePod.addJsonPatch(JsonPatch.replace('/spec/enableServiceLinks', true));
	//
	AddJsonPatch(ops ...JsonPatch)
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if there the construct is valid.
	// Deprecated: use `Node.addValidation()` to subscribe validation functions on this construct
	// instead of overriding this method.
	OnValidate() *[]*string
	// Renders the object to Kubernetes JSON.
	//
	// To disable sorting of dictionary keys in output object set the
	// `CDK8S_DISABLE_SORT` environment variable to any non-empty value.
	ToJson() interface{}
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for ApiObject
type jsiiProxy_ApiObject struct {
	internal.Type__constructsConstruct
}

func (j *jsiiProxy_ApiObject) ApiGroup() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiGroup",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiObject) ApiVersion() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiVersion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiObject) Chart() Chart {
	var returns Chart
	_jsii_.Get(
		j,
		"chart",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiObject) Kind() *string {
	var returns *string
	_jsii_.Get(
		j,
		"kind",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiObject) Metadata() ApiObjectMetadataDefinition {
	var returns ApiObjectMetadataDefinition
	_jsii_.Get(
		j,
		"metadata",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiObject) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}


// Defines an API object.
func NewApiObject(scope constructs.Construct, id *string, props *ApiObjectProps) ApiObject {
	_init_.Initialize()

	j := jsiiProxy_ApiObject{}

	_jsii_.Create(
		"cdk8s.ApiObject",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Defines an API object.
func NewApiObject_Override(a ApiObject, scope constructs.Construct, id *string, props *ApiObjectProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk8s.ApiObject",
		[]interface{}{scope, id, props},
		a,
	)
}

// Returns the `ApiObject` named `Resource` which is a child of the given construct.
//
// If `c` is an `ApiObject`, it is returned directly. Throws an
// exception if the construct does not have a child named `Default` _or_ if
// this child is not an `ApiObject`.
func ApiObject_Of(c constructs.IConstruct) ApiObject {
	_init_.Initialize()

	var returns ApiObject

	_jsii_.StaticInvoke(
		"cdk8s.ApiObject",
		"of",
		[]interface{}{c},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiObject) AddDependency(dependencies ...constructs.IConstruct) {
	args := []interface{}{}
	for _, a := range dependencies {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		a,
		"addDependency",
		args,
	)
}

func (a *jsiiProxy_ApiObject) AddJsonPatch(ops ...JsonPatch) {
	args := []interface{}{}
	for _, a := range ops {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		a,
		"addJsonPatch",
		args,
	)
}

func (a *jsiiProxy_ApiObject) OnPrepare() {
	_jsii_.InvokeVoid(
		a,
		"onPrepare",
		nil, // no parameters
	)
}

func (a *jsiiProxy_ApiObject) OnSynthesize(session constructs.ISynthesisSession) {
	_jsii_.InvokeVoid(
		a,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (a *jsiiProxy_ApiObject) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		a,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiObject) ToJson() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		a,
		"toJson",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiObject) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

// Metadata associated with this object.
type ApiObjectMetadata struct {
	// Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.
	//
	// They are not queryable and should be
	// preserved when modifying objects.
	// See: http://kubernetes.io/docs/user-guide/annotations
	//
	Annotations *map[string]*string `json:"annotations" yaml:"annotations"`
	// Namespaced keys that tell Kubernetes to wait until specific conditions are met before it fully deletes resources marked for deletion.
	//
	// Must be empty before the object is deleted from the registry. Each entry is
	// an identifier for the responsible component that will remove the entry from
	// the list. If the deletionTimestamp of the object is non-nil, entries in
	// this list can only be removed. Finalizers may be processed and removed in
	// any order.  Order is NOT enforced because it introduces significant risk of
	// stuck finalizers. finalizers is a shared field, any actor with permission
	// can reorder it. If the finalizer list is processed in order, then this can
	// lead to a situation in which the component responsible for the first
	// finalizer in the list is waiting for a signal (field value, external
	// system, or other) produced by a component responsible for a finalizer later
	// in the list, resulting in a deadlock. Without enforced ordering finalizers
	// are free to order amongst themselves and are not vulnerable to ordering
	// changes in the list.
	// See: https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/
	//
	Finalizers *[]*string `json:"finalizers" yaml:"finalizers"`
	// Map of string keys and values that can be used to organize and categorize (scope and select) objects.
	//
	// May match selectors of replication controllers and services.
	// See: http://kubernetes.io/docs/user-guide/labels
	//
	Labels *map[string]*string `json:"labels" yaml:"labels"`
	// The unique, namespace-global, name of this object inside the Kubernetes cluster.
	//
	// Normally, you shouldn't specify names for objects and let the CDK generate
	// a name for you that is application-unique. The names CDK generates are
	// composed from the construct path components, separated by dots and a suffix
	// that is based on a hash of the entire path, to ensure uniqueness.
	//
	// You can supply custom name allocation logic by overriding the
	// `chart.generateObjectName` method.
	//
	// If you use an explicit name here, bear in mind that this reduces the
	// composability of your construct because it won't be possible to include
	// more than one instance in any app. Therefore it is highly recommended to
	// leave this unspecified.
	Name *string `json:"name" yaml:"name"`
	// Namespace defines the space within each name must be unique.
	//
	// An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation.
	// Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty. Must be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces
	Namespace *string `json:"namespace" yaml:"namespace"`
	// List of objects depended by this object.
	//
	// If ALL objects in the list have
	// been deleted, this object will be garbage collected. If this object is
	// managed by a controller, then an entry in this list will point to this
	// controller, with the controller field set to true. There cannot be more
	// than one managing controller.
	//
	// Kubernetes sets the value of this field automatically for objects that are
	// dependents of other objects like ReplicaSets, DaemonSets, Deployments, Jobs
	// and CronJobs, and ReplicationControllers. You can also configure these
	// relationships manually by changing the value of this field. However, you
	// usually don't need to and can allow Kubernetes to automatically manage the
	// relationships.
	// See: https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/
	//
	OwnerReferences *[]*OwnerReference `json:"ownerReferences" yaml:"ownerReferences"`
}

// Object metadata.
type ApiObjectMetadataDefinition interface {
	// The name of the API object.
	//
	// If a name is specified in `metadata.name` this will be the name returned.
	// Otherwise, a name will be generated by calling
	// `Chart.of(this).generatedObjectName(this)`, which by default uses the
	// construct path to generate a DNS-compatible name for the resource.
	Name() *string
	// The object's namespace.
	Namespace() *string
	// Adds an arbitrary key/value to the object metadata.
	Add(key *string, value interface{})
	// Add an annotation.
	AddAnnotation(key *string, value *string)
	// Add one or more finalizers.
	AddFinalizers(finalizers ...*string)
	// Add a label.
	AddLabel(key *string, value *string)
	// Add an owner.
	AddOwnerReference(owner *OwnerReference)
	// Returns: a value of a label or undefined.
	GetLabel(key *string) *string
	// Synthesizes a k8s ObjectMeta for this metadata set.
	ToJson() interface{}
}

// The jsii proxy struct for ApiObjectMetadataDefinition
type jsiiProxy_ApiObjectMetadataDefinition struct {
	_ byte // padding
}

func (j *jsiiProxy_ApiObjectMetadataDefinition) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiObjectMetadataDefinition) Namespace() *string {
	var returns *string
	_jsii_.Get(
		j,
		"namespace",
		&returns,
	)
	return returns
}


func NewApiObjectMetadataDefinition(options *ApiObjectMetadata) ApiObjectMetadataDefinition {
	_init_.Initialize()

	j := jsiiProxy_ApiObjectMetadataDefinition{}

	_jsii_.Create(
		"cdk8s.ApiObjectMetadataDefinition",
		[]interface{}{options},
		&j,
	)

	return &j
}

func NewApiObjectMetadataDefinition_Override(a ApiObjectMetadataDefinition, options *ApiObjectMetadata) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk8s.ApiObjectMetadataDefinition",
		[]interface{}{options},
		a,
	)
}

func (a *jsiiProxy_ApiObjectMetadataDefinition) Add(key *string, value interface{}) {
	_jsii_.InvokeVoid(
		a,
		"add",
		[]interface{}{key, value},
	)
}

func (a *jsiiProxy_ApiObjectMetadataDefinition) AddAnnotation(key *string, value *string) {
	_jsii_.InvokeVoid(
		a,
		"addAnnotation",
		[]interface{}{key, value},
	)
}

func (a *jsiiProxy_ApiObjectMetadataDefinition) AddFinalizers(finalizers ...*string) {
	args := []interface{}{}
	for _, a := range finalizers {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		a,
		"addFinalizers",
		args,
	)
}

func (a *jsiiProxy_ApiObjectMetadataDefinition) AddLabel(key *string, value *string) {
	_jsii_.InvokeVoid(
		a,
		"addLabel",
		[]interface{}{key, value},
	)
}

func (a *jsiiProxy_ApiObjectMetadataDefinition) AddOwnerReference(owner *OwnerReference) {
	_jsii_.InvokeVoid(
		a,
		"addOwnerReference",
		[]interface{}{owner},
	)
}

func (a *jsiiProxy_ApiObjectMetadataDefinition) GetLabel(key *string) *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"getLabel",
		[]interface{}{key},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiObjectMetadataDefinition) ToJson() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		a,
		"toJson",
		nil, // no parameters
		&returns,
	)

	return returns
}

// Options for defining API objects.
type ApiObjectProps struct {
	// API version.
	ApiVersion *string `json:"apiVersion" yaml:"apiVersion"`
	// Resource kind.
	Kind *string `json:"kind" yaml:"kind"`
	// Object metadata.
	//
	// If `name` is not specified, an app-unique name will be allocated by the
	// framework based on the path of the construct within thes construct tree.
	Metadata *ApiObjectMetadata `json:"metadata" yaml:"metadata"`
}

// Represents a cdk8s application.
type App interface {
	constructs.Construct
	// Returns all the charts in this app, sorted topologically.
	Charts() *[]Chart
	// The output directory into which manifests will be synthesized.
	Outdir() *string
	// The file extension to use for rendered YAML files.
	OutputFileExtension() *string
	// How to divide the YAML output into files.
	YamlOutputType() YamlOutputType
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if there the construct is valid.
	// Deprecated: use `Node.addValidation()` to subscribe validation functions on this construct
	// instead of overriding this method.
	OnValidate() *[]*string
	// Synthesizes all manifests to the output directory.
	Synth()
	// Synthesizes the app into a YAML string.
	//
	// Returns: A string with all YAML objects across all charts in this app.
	SynthYaml() interface{}
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for App
type jsiiProxy_App struct {
	internal.Type__constructsConstruct
}

func (j *jsiiProxy_App) Charts() *[]Chart {
	var returns *[]Chart
	_jsii_.Get(
		j,
		"charts",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_App) Outdir() *string {
	var returns *string
	_jsii_.Get(
		j,
		"outdir",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_App) OutputFileExtension() *string {
	var returns *string
	_jsii_.Get(
		j,
		"outputFileExtension",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_App) YamlOutputType() YamlOutputType {
	var returns YamlOutputType
	_jsii_.Get(
		j,
		"yamlOutputType",
		&returns,
	)
	return returns
}


// Defines an app.
func NewApp(props *AppProps) App {
	_init_.Initialize()

	j := jsiiProxy_App{}

	_jsii_.Create(
		"cdk8s.App",
		[]interface{}{props},
		&j,
	)

	return &j
}

// Defines an app.
func NewApp_Override(a App, props *AppProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk8s.App",
		[]interface{}{props},
		a,
	)
}

func (a *jsiiProxy_App) OnPrepare() {
	_jsii_.InvokeVoid(
		a,
		"onPrepare",
		nil, // no parameters
	)
}

func (a *jsiiProxy_App) OnSynthesize(session constructs.ISynthesisSession) {
	_jsii_.InvokeVoid(
		a,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (a *jsiiProxy_App) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		a,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_App) Synth() {
	_jsii_.InvokeVoid(
		a,
		"synth",
		nil, // no parameters
	)
}

func (a *jsiiProxy_App) SynthYaml() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		a,
		"synthYaml",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_App) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

type AppProps struct {
	// The directory to output Kubernetes manifests.
	Outdir *string `json:"outdir" yaml:"outdir"`
	// The file extension to use for rendered YAML files.
	OutputFileExtension *string `json:"outputFileExtension" yaml:"outputFileExtension"`
	// How to divide the YAML output into files.
	YamlOutputType YamlOutputType `json:"yamlOutputType" yaml:"yamlOutputType"`
}

type Chart interface {
	constructs.Construct
	// Labels applied to all resources in this chart.
	//
	// This is an immutable copy.
	Labels() *map[string]*string
	// The default namespace for all objects in this chart.
	Namespace() *string
	// Create a dependency between this Chart and other constructs.
	//
	// These can be other ApiObjects, Charts, or custom.
	AddDependency(dependencies ...constructs.IConstruct)
	// Generates a app-unique name for an object given it's construct node path.
	//
	// Different resource types may have different constraints on names
	// (`metadata.name`). The previous version of the name generator was
	// compatible with DNS_SUBDOMAIN but not with DNS_LABEL.
	//
	// For example, `Deployment` names must comply with DNS_SUBDOMAIN while
	// `Service` names must comply with DNS_LABEL.
	//
	// Since there is no formal specification for this, the default name
	// generation scheme for kubernetes objects in cdk8s was changed to DNS_LABEL,
	// since it’s the common denominator for all kubernetes resources
	// (supposedly).
	//
	// You can override this method if you wish to customize object names at the
	// chart level.
	GenerateObjectName(apiObject ApiObject) *string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if there the construct is valid.
	// Deprecated: use `Node.addValidation()` to subscribe validation functions on this construct
	// instead of overriding this method.
	OnValidate() *[]*string
	// Renders this chart to a set of Kubernetes JSON resources.
	//
	// Returns: array of resource manifests.
	ToJson() *[]interface{}
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for Chart
type jsiiProxy_Chart struct {
	internal.Type__constructsConstruct
}

func (j *jsiiProxy_Chart) Labels() *map[string]*string {
	var returns *map[string]*string
	_jsii_.Get(
		j,
		"labels",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Chart) Namespace() *string {
	var returns *string
	_jsii_.Get(
		j,
		"namespace",
		&returns,
	)
	return returns
}


func NewChart(scope constructs.Construct, id *string, props *ChartProps) Chart {
	_init_.Initialize()

	j := jsiiProxy_Chart{}

	_jsii_.Create(
		"cdk8s.Chart",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewChart_Override(c Chart, scope constructs.Construct, id *string, props *ChartProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk8s.Chart",
		[]interface{}{scope, id, props},
		c,
	)
}

// Finds the chart in which a node is defined.
func Chart_Of(c constructs.IConstruct) Chart {
	_init_.Initialize()

	var returns Chart

	_jsii_.StaticInvoke(
		"cdk8s.Chart",
		"of",
		[]interface{}{c},
		&returns,
	)

	return returns
}

func (c *jsiiProxy_Chart) AddDependency(dependencies ...constructs.IConstruct) {
	args := []interface{}{}
	for _, a := range dependencies {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		c,
		"addDependency",
		args,
	)
}

func (c *jsiiProxy_Chart) GenerateObjectName(apiObject ApiObject) *string {
	var returns *string

	_jsii_.Invoke(
		c,
		"generateObjectName",
		[]interface{}{apiObject},
		&returns,
	)

	return returns
}

func (c *jsiiProxy_Chart) OnPrepare() {
	_jsii_.InvokeVoid(
		c,
		"onPrepare",
		nil, // no parameters
	)
}

func (c *jsiiProxy_Chart) OnSynthesize(session constructs.ISynthesisSession) {
	_jsii_.InvokeVoid(
		c,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (c *jsiiProxy_Chart) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		c,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (c *jsiiProxy_Chart) ToJson() *[]interface{} {
	var returns *[]interface{}

	_jsii_.Invoke(
		c,
		"toJson",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (c *jsiiProxy_Chart) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		c,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

type ChartProps struct {
	// Labels to apply to all resources in this chart.
	Labels *map[string]*string `json:"labels" yaml:"labels"`
	// The default namespace for all objects defined in this chart (directly or indirectly).
	//
	// This namespace will only apply to objects that don't have a
	// `namespace` explicitly defined for them.
	Namespace *string `json:"namespace" yaml:"namespace"`
}

// Represents the dependency graph for a given Node.
//
// This graph includes the dependency relationships between all nodes in the
// node (construct) sub-tree who's root is this Node.
//
// Note that this means that lonely nodes (no dependencies and no dependants) are also included in this graph as
// childless children of the root node of the graph.
//
// The graph does not include cross-scope dependencies. That is, if a child on the current scope depends on a node
// from a different scope, that relationship is not represented in this graph.
type DependencyGraph interface {
	// Returns the root of the graph.
	//
	// Note that this vertex will always have `null` as its `.value` since it is an artifical root
	// that binds all the connected spaces of the graph.
	Root() DependencyVertex
	// See: Vertex.topology()
	//
	Topology() *[]constructs.IConstruct
}

// The jsii proxy struct for DependencyGraph
type jsiiProxy_DependencyGraph struct {
	_ byte // padding
}

func (j *jsiiProxy_DependencyGraph) Root() DependencyVertex {
	var returns DependencyVertex
	_jsii_.Get(
		j,
		"root",
		&returns,
	)
	return returns
}


func NewDependencyGraph(node constructs.Node) DependencyGraph {
	_init_.Initialize()

	j := jsiiProxy_DependencyGraph{}

	_jsii_.Create(
		"cdk8s.DependencyGraph",
		[]interface{}{node},
		&j,
	)

	return &j
}

func NewDependencyGraph_Override(d DependencyGraph, node constructs.Node) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk8s.DependencyGraph",
		[]interface{}{node},
		d,
	)
}

func (d *jsiiProxy_DependencyGraph) Topology() *[]constructs.IConstruct {
	var returns *[]constructs.IConstruct

	_jsii_.Invoke(
		d,
		"topology",
		nil, // no parameters
		&returns,
	)

	return returns
}

// Represents a vertex in the graph.
//
// The value of each vertex is an `IConstruct` that is accessible via the `.value` getter.
type DependencyVertex interface {
	// Returns the parents of the vertex (i.e dependants).
	Inbound() *[]DependencyVertex
	// Returns the children of the vertex (i.e dependencies).
	Outbound() *[]DependencyVertex
	// Returns the IConstruct this graph vertex represents.
	//
	// `null` in case this is the root of the graph.
	Value() constructs.IConstruct
	// Adds a vertex as a dependency of the current node.
	//
	// Also updates the parents of `dep`, so that it contains this node as a parent.
	//
	// This operation will fail in case it creates a cycle in the graph.
	AddChild(dep DependencyVertex)
	// Returns a topologically sorted array of the constructs in the sub-graph.
	Topology() *[]constructs.IConstruct
}

// The jsii proxy struct for DependencyVertex
type jsiiProxy_DependencyVertex struct {
	_ byte // padding
}

func (j *jsiiProxy_DependencyVertex) Inbound() *[]DependencyVertex {
	var returns *[]DependencyVertex
	_jsii_.Get(
		j,
		"inbound",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DependencyVertex) Outbound() *[]DependencyVertex {
	var returns *[]DependencyVertex
	_jsii_.Get(
		j,
		"outbound",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DependencyVertex) Value() constructs.IConstruct {
	var returns constructs.IConstruct
	_jsii_.Get(
		j,
		"value",
		&returns,
	)
	return returns
}


func NewDependencyVertex(value constructs.IConstruct) DependencyVertex {
	_init_.Initialize()

	j := jsiiProxy_DependencyVertex{}

	_jsii_.Create(
		"cdk8s.DependencyVertex",
		[]interface{}{value},
		&j,
	)

	return &j
}

func NewDependencyVertex_Override(d DependencyVertex, value constructs.IConstruct) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk8s.DependencyVertex",
		[]interface{}{value},
		d,
	)
}

func (d *jsiiProxy_DependencyVertex) AddChild(dep DependencyVertex) {
	_jsii_.InvokeVoid(
		d,
		"addChild",
		[]interface{}{dep},
	)
}

func (d *jsiiProxy_DependencyVertex) Topology() *[]constructs.IConstruct {
	var returns *[]constructs.IConstruct

	_jsii_.Invoke(
		d,
		"topology",
		nil, // no parameters
		&returns,
	)

	return returns
}

// Represents a length of time.
//
// The amount can be specified either as a literal value (e.g: `10`) which
// cannot be negative.
type Duration interface {
	// Return the total number of days in this Duration.
	//
	// Returns: the value of this `Duration` expressed in Days.
	ToDays(opts *TimeConversionOptions) *float64
	// Return the total number of hours in this Duration.
	//
	// Returns: the value of this `Duration` expressed in Hours.
	ToHours(opts *TimeConversionOptions) *float64
	// Turn this duration into a human-readable string.
	ToHumanString() *string
	// Return an ISO 8601 representation of this period.
	//
	// Returns: a string starting with 'PT' describing the period.
	// See: https://www.iso.org/fr/standard/70907.html
	//
	ToIsoString() *string
	// Return the total number of milliseconds in this Duration.
	//
	// Returns: the value of this `Duration` expressed in Milliseconds.
	ToMilliseconds(opts *TimeConversionOptions) *float64
	// Return the total number of minutes in this Duration.
	//
	// Returns: the value of this `Duration` expressed in Minutes.
	ToMinutes(opts *TimeConversionOptions) *float64
	// Return the total number of seconds in this Duration.
	//
	// Returns: the value of this `Duration` expressed in Seconds.
	ToSeconds(opts *TimeConversionOptions) *float64
}

// The jsii proxy struct for Duration
type jsiiProxy_Duration struct {
	_ byte // padding
}

// Create a Duration representing an amount of days.
//
// Returns: a new `Duration` representing `amount` Days.
func Duration_Days(amount *float64) Duration {
	_init_.Initialize()

	var returns Duration

	_jsii_.StaticInvoke(
		"cdk8s.Duration",
		"days",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

// Create a Duration representing an amount of hours.
//
// Returns: a new `Duration` representing `amount` Hours.
func Duration_Hours(amount *float64) Duration {
	_init_.Initialize()

	var returns Duration

	_jsii_.StaticInvoke(
		"cdk8s.Duration",
		"hours",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

// Create a Duration representing an amount of milliseconds.
//
// Returns: a new `Duration` representing `amount` ms.
func Duration_Millis(amount *float64) Duration {
	_init_.Initialize()

	var returns Duration

	_jsii_.StaticInvoke(
		"cdk8s.Duration",
		"millis",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

// Create a Duration representing an amount of minutes.
//
// Returns: a new `Duration` representing `amount` Minutes.
func Duration_Minutes(amount *float64) Duration {
	_init_.Initialize()

	var returns Duration

	_jsii_.StaticInvoke(
		"cdk8s.Duration",
		"minutes",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

// Parse a period formatted according to the ISO 8601 standard.
//
// Returns: the parsed `Duration`.
// See: https://www.iso.org/fr/standard/70907.html
//
func Duration_Parse(duration *string) Duration {
	_init_.Initialize()

	var returns Duration

	_jsii_.StaticInvoke(
		"cdk8s.Duration",
		"parse",
		[]interface{}{duration},
		&returns,
	)

	return returns
}

// Create a Duration representing an amount of seconds.
//
// Returns: a new `Duration` representing `amount` Seconds.
func Duration_Seconds(amount *float64) Duration {
	_init_.Initialize()

	var returns Duration

	_jsii_.StaticInvoke(
		"cdk8s.Duration",
		"seconds",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Duration) ToDays(opts *TimeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		d,
		"toDays",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Duration) ToHours(opts *TimeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		d,
		"toHours",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Duration) ToHumanString() *string {
	var returns *string

	_jsii_.Invoke(
		d,
		"toHumanString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Duration) ToIsoString() *string {
	var returns *string

	_jsii_.Invoke(
		d,
		"toIsoString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Duration) ToMilliseconds(opts *TimeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		d,
		"toMilliseconds",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Duration) ToMinutes(opts *TimeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		d,
		"toMinutes",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Duration) ToSeconds(opts *TimeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		d,
		"toSeconds",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

type GroupVersionKind struct {
	// The object's API version (e.g. `authorization.k8s.io/v1`).
	ApiVersion *string `json:"apiVersion" yaml:"apiVersion"`
	// The object kind.
	Kind *string `json:"kind" yaml:"kind"`
}

// Represents a Helm deployment.
//
// Use this construct to import an existing Helm chart and incorporate it into your constructs.
type Helm interface {
	Include
	// Returns all the included API objects.
	ApiObjects() *[]ApiObject
	// The helm release name.
	ReleaseName() *string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if there the construct is valid.
	// Deprecated: use `Node.addValidation()` to subscribe validation functions on this construct
	// instead of overriding this method.
	OnValidate() *[]*string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for Helm
type jsiiProxy_Helm struct {
	jsiiProxy_Include
}

func (j *jsiiProxy_Helm) ApiObjects() *[]ApiObject {
	var returns *[]ApiObject
	_jsii_.Get(
		j,
		"apiObjects",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Helm) ReleaseName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"releaseName",
		&returns,
	)
	return returns
}


func NewHelm(scope constructs.Construct, id *string, props *HelmProps) Helm {
	_init_.Initialize()

	j := jsiiProxy_Helm{}

	_jsii_.Create(
		"cdk8s.Helm",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewHelm_Override(h Helm, scope constructs.Construct, id *string, props *HelmProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk8s.Helm",
		[]interface{}{scope, id, props},
		h,
	)
}

func (h *jsiiProxy_Helm) OnPrepare() {
	_jsii_.InvokeVoid(
		h,
		"onPrepare",
		nil, // no parameters
	)
}

func (h *jsiiProxy_Helm) OnSynthesize(session constructs.ISynthesisSession) {
	_jsii_.InvokeVoid(
		h,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (h *jsiiProxy_Helm) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		h,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (h *jsiiProxy_Helm) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		h,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

// Options for `Helm`.
type HelmProps struct {
	// The chart name to use. It can be a chart from a helm repository or a local directory.
	//
	// This name is passed to `helm template` and has all the relevant semantics.
	//
	// Example:
	//   "bitnami/redis"
	//
	Chart *string `json:"chart" yaml:"chart"`
	// The local helm executable to use in order to create the manifest the chart.
	HelmExecutable *string `json:"helmExecutable" yaml:"helmExecutable"`
	// Additional flags to add to the `helm` execution.
	HelmFlags *[]*string `json:"helmFlags" yaml:"helmFlags"`
	// The release name.
	// See: https://helm.sh/docs/intro/using_helm/#three-big-concepts
	//
	ReleaseName *string `json:"releaseName" yaml:"releaseName"`
	// Values to pass to the chart.
	Values *map[string]interface{} `json:"values" yaml:"values"`
}

type IAnyProducer interface {
	Produce() interface{}
}

// The jsii proxy for IAnyProducer
type jsiiProxy_IAnyProducer struct {
	_ byte // padding
}

func (i *jsiiProxy_IAnyProducer) Produce() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		i,
		"produce",
		nil, // no parameters
		&returns,
	)

	return returns
}

// Reads a YAML manifest from a file or a URL and defines all resources as API objects within the defined scope.
//
// The names (`metadata.name`) of imported resources will be preserved as-is
// from the manifest.
type Include interface {
	constructs.Construct
	// Returns all the included API objects.
	ApiObjects() *[]ApiObject
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if there the construct is valid.
	// Deprecated: use `Node.addValidation()` to subscribe validation functions on this construct
	// instead of overriding this method.
	OnValidate() *[]*string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for Include
type jsiiProxy_Include struct {
	internal.Type__constructsConstruct
}

func (j *jsiiProxy_Include) ApiObjects() *[]ApiObject {
	var returns *[]ApiObject
	_jsii_.Get(
		j,
		"apiObjects",
		&returns,
	)
	return returns
}


func NewInclude(scope constructs.Construct, id *string, props *IncludeProps) Include {
	_init_.Initialize()

	j := jsiiProxy_Include{}

	_jsii_.Create(
		"cdk8s.Include",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewInclude_Override(i Include, scope constructs.Construct, id *string, props *IncludeProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk8s.Include",
		[]interface{}{scope, id, props},
		i,
	)
}

func (i *jsiiProxy_Include) OnPrepare() {
	_jsii_.InvokeVoid(
		i,
		"onPrepare",
		nil, // no parameters
	)
}

func (i *jsiiProxy_Include) OnSynthesize(session constructs.ISynthesisSession) {
	_jsii_.InvokeVoid(
		i,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (i *jsiiProxy_Include) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		i,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_Include) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

type IncludeProps struct {
	// Local file path or URL which includes a Kubernetes YAML manifest.
	//
	// Example:
	//   mymanifest.yaml
	//
	Url *string `json:"url" yaml:"url"`
}

// Utility for applying RFC-6902 JSON-Patch to a document.
//
// Use the the `JsonPatch.apply(doc, ...ops)` function to apply a set of
// operations to a JSON document and return the result.
//
// Operations can be created using the factory methods `JsonPatch.add()`,
// `JsonPatch.remove()`, etc.
//
// Example:
//   const output = JsonPatch.apply(input,
//    JsonPatch.replace('/world/hi/there', 'goodbye'),
//    JsonPatch.add('/world/foo/', 'boom'),
//    JsonPatch.remove('/hello'));
//
type JsonPatch interface {
}

// The jsii proxy struct for JsonPatch
type jsiiProxy_JsonPatch struct {
	_ byte // padding
}

// Adds a value to an object or inserts it into an array.
//
// In the case of an
// array, the value is inserted before the given index. The - character can be
// used instead of an index to insert at the end of an array.
//
// Example:
//   JsonPatch.add('/biscuits/1', { "name": "Ginger Nut" })
//
func JsonPatch_Add(path *string, value interface{}) JsonPatch {
	_init_.Initialize()

	var returns JsonPatch

	_jsii_.StaticInvoke(
		"cdk8s.JsonPatch",
		"add",
		[]interface{}{path, value},
		&returns,
	)

	return returns
}

// Applies a set of JSON-Patch (RFC-6902) operations to `document` and returns the result.
//
// Returns: The result document.
func JsonPatch_Apply(document interface{}, ops ...JsonPatch) interface{} {
	_init_.Initialize()

	args := []interface{}{document}
	for _, a := range ops {
		args = append(args, a)
	}

	var returns interface{}

	_jsii_.StaticInvoke(
		"cdk8s.JsonPatch",
		"apply",
		args,
		&returns,
	)

	return returns
}

// Copies a value from one location to another within the JSON document.
//
// Both
// from and path are JSON Pointers.
//
// Example:
//   JsonPatch.copy('/biscuits/0', '/best_biscuit')
//
func JsonPatch_Copy(from *string, path *string) JsonPatch {
	_init_.Initialize()

	var returns JsonPatch

	_jsii_.StaticInvoke(
		"cdk8s.JsonPatch",
		"copy",
		[]interface{}{from, path},
		&returns,
	)

	return returns
}

// Moves a value from one location to the other.
//
// Both from and path are JSON Pointers.
//
// Example:
//   JsonPatch.move('/biscuits', '/cookies')
//
func JsonPatch_Move(from *string, path *string) JsonPatch {
	_init_.Initialize()

	var returns JsonPatch

	_jsii_.StaticInvoke(
		"cdk8s.JsonPatch",
		"move",
		[]interface{}{from, path},
		&returns,
	)

	return returns
}

// Removes a value from an object or array.
//
// Example:
//   JsonPatch.remove('/biscuits/0')
//
func JsonPatch_Remove(path *string) JsonPatch {
	_init_.Initialize()

	var returns JsonPatch

	_jsii_.StaticInvoke(
		"cdk8s.JsonPatch",
		"remove",
		[]interface{}{path},
		&returns,
	)

	return returns
}

// Replaces a value.
//
// Equivalent to a “remove” followed by an “add”.
//
// Example:
//   JsonPatch.replace('/biscuits/0/name', 'Chocolate Digestive')
//
func JsonPatch_Replace(path *string, value interface{}) JsonPatch {
	_init_.Initialize()

	var returns JsonPatch

	_jsii_.StaticInvoke(
		"cdk8s.JsonPatch",
		"replace",
		[]interface{}{path, value},
		&returns,
	)

	return returns
}

// Tests that the specified value is set in the document.
//
// If the test fails,
// then the patch as a whole should not apply.
//
// Example:
//   JsonPatch.test('/best_biscuit/name', 'Choco Leibniz')
//
func JsonPatch_Test(path *string, value interface{}) JsonPatch {
	_init_.Initialize()

	var returns JsonPatch

	_jsii_.StaticInvoke(
		"cdk8s.JsonPatch",
		"test",
		[]interface{}{path, value},
		&returns,
	)

	return returns
}

type Lazy interface {
	Produce() interface{}
}

// The jsii proxy struct for Lazy
type jsiiProxy_Lazy struct {
	_ byte // padding
}

func Lazy_Any(producer IAnyProducer) interface{} {
	_init_.Initialize()

	var returns interface{}

	_jsii_.StaticInvoke(
		"cdk8s.Lazy",
		"any",
		[]interface{}{producer},
		&returns,
	)

	return returns
}

func (l *jsiiProxy_Lazy) Produce() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		l,
		"produce",
		nil, // no parameters
		&returns,
	)

	return returns
}

// Options for name generation.
type NameOptions struct {
	// Delimiter to use between components.
	Delimiter *string `json:"delimiter" yaml:"delimiter"`
	// Extra components to include in the name.
	Extra *[]*string `json:"extra" yaml:"extra"`
	// Include a short hash as last part of the name.
	IncludeHash *bool `json:"includeHash" yaml:"includeHash"`
	// Maximum allowed length for the name.
	MaxLen *float64 `json:"maxLen" yaml:"maxLen"`
}

// Utilities for generating unique and stable names.
type Names interface {
}

// The jsii proxy struct for Names
type jsiiProxy_Names struct {
	_ byte // padding
}

// Generates a unique and stable name compatible DNS_LABEL from RFC-1123 from a path.
//
// The generated name will:
//   - contain at most 63 characters
//   - contain only lowercase alphanumeric characters or ‘-’
//   - start with an alphanumeric character
//   - end with an alphanumeric character
//
// The generated name will have the form:
//   <comp0>-<comp1>-..-<compN>-<short-hash>
//
// Where <comp> are the path components (assuming they are is separated by
// "/").
//
// Note that if the total length is longer than 63 characters, we will trim
// the first components since the last components usually encode more meaning.
func Names_ToDnsLabel(scope constructs.Construct, options *NameOptions) *string {
	_init_.Initialize()

	var returns *string

	_jsii_.StaticInvoke(
		"cdk8s.Names",
		"toDnsLabel",
		[]interface{}{scope, options},
		&returns,
	)

	return returns
}

// Generates a unique and stable name compatible label key name segment and label value from a path.
//
// The name segment is required and must be 63 characters or less, beginning
// and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-),
// underscores (_), dots (.), and alphanumerics between.
//
// Valid label values must be 63 characters or less and must be empty or
// begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes
// (-), underscores (_), dots (.), and alphanumerics between.
//
// The generated name will have the form:
//   <comp0><delim><comp1><delim>..<delim><compN><delim><short-hash>
//
// Where <comp> are the path components (assuming they are is separated by
// "/").
//
// Note that if the total length is longer than 63 characters, we will trim
// the first components since the last components usually encode more meaning.
func Names_ToLabelValue(scope constructs.Construct, options *NameOptions) *string {
	_init_.Initialize()

	var returns *string

	_jsii_.StaticInvoke(
		"cdk8s.Names",
		"toLabelValue",
		[]interface{}{scope, options},
		&returns,
	)

	return returns
}

// OwnerReference contains enough information to let you identify an owning object.
//
// An owning object must be in the same namespace as the dependent, or
// be cluster-scoped, so there is no namespace field.
type OwnerReference struct {
	// API version of the referent.
	ApiVersion *string `json:"apiVersion" yaml:"apiVersion"`
	// Kind of the referent.
	// See: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	//
	Kind *string `json:"kind" yaml:"kind"`
	// Name of the referent.
	// See: http://kubernetes.io/docs/user-guide/identifiers#names
	//
	Name *string `json:"name" yaml:"name"`
	// UID of the referent.
	// See: http://kubernetes.io/docs/user-guide/identifiers#uids
	//
	Uid *string `json:"uid" yaml:"uid"`
	// If true, AND if the owner has the "foregroundDeletion" finalizer, then the owner cannot be deleted from the key-value store until this reference is removed.
	//
	// Defaults to false. To set this field, a user needs "delete"
	// permission of the owner, otherwise 422 (Unprocessable Entity) will be
	// returned.
	BlockOwnerDeletion *bool `json:"blockOwnerDeletion" yaml:"blockOwnerDeletion"`
	// If true, this reference points to the managing controller.
	Controller *bool `json:"controller" yaml:"controller"`
}

// Represents the amount of digital storage.
//
// The amount can be specified either as a literal value (e.g: `10`) which
// cannot be negative.
//
// When the amount is passed as a token, unit conversion is not possible.
type Size interface {
	// Return this storage as a total number of gibibytes.
	ToGibibytes(opts *SizeConversionOptions) *float64
	// Return this storage as a total number of kibibytes.
	ToKibibytes(opts *SizeConversionOptions) *float64
	// Return this storage as a total number of mebibytes.
	ToMebibytes(opts *SizeConversionOptions) *float64
	// Return this storage as a total number of pebibytes.
	ToPebibytes(opts *SizeConversionOptions) *float64
	// Return this storage as a total number of tebibytes.
	ToTebibytes(opts *SizeConversionOptions) *float64
}

// The jsii proxy struct for Size
type jsiiProxy_Size struct {
	_ byte // padding
}

// Create a Storage representing an amount gibibytes.
//
// 1 GiB = 1024 MiB.
func Size_Gibibytes(amount *float64) Size {
	_init_.Initialize()

	var returns Size

	_jsii_.StaticInvoke(
		"cdk8s.Size",
		"gibibytes",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

// Create a Storage representing an amount kibibytes.
//
// 1 KiB = 1024 bytes.
func Size_Kibibytes(amount *float64) Size {
	_init_.Initialize()

	var returns Size

	_jsii_.StaticInvoke(
		"cdk8s.Size",
		"kibibytes",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

// Create a Storage representing an amount mebibytes.
//
// 1 MiB = 1024 KiB.
func Size_Mebibytes(amount *float64) Size {
	_init_.Initialize()

	var returns Size

	_jsii_.StaticInvoke(
		"cdk8s.Size",
		"mebibytes",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

// Create a Storage representing an amount pebibytes.
//
// 1 PiB = 1024 TiB.
func Size_Pebibyte(amount *float64) Size {
	_init_.Initialize()

	var returns Size

	_jsii_.StaticInvoke(
		"cdk8s.Size",
		"pebibyte",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

// Create a Storage representing an amount tebibytes.
//
// 1 TiB = 1024 GiB.
func Size_Tebibytes(amount *float64) Size {
	_init_.Initialize()

	var returns Size

	_jsii_.StaticInvoke(
		"cdk8s.Size",
		"tebibytes",
		[]interface{}{amount},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_Size) ToGibibytes(opts *SizeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		s,
		"toGibibytes",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_Size) ToKibibytes(opts *SizeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		s,
		"toKibibytes",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_Size) ToMebibytes(opts *SizeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		s,
		"toMebibytes",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_Size) ToPebibytes(opts *SizeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		s,
		"toPebibytes",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_Size) ToTebibytes(opts *SizeConversionOptions) *float64 {
	var returns *float64

	_jsii_.Invoke(
		s,
		"toTebibytes",
		[]interface{}{opts},
		&returns,
	)

	return returns
}

// Options for how to convert time to a different unit.
type SizeConversionOptions struct {
	// How conversions should behave when it encounters a non-integer result.
	Rounding SizeRoundingBehavior `json:"rounding" yaml:"rounding"`
}

// Rounding behaviour when converting between units of `Size`.
type SizeRoundingBehavior string

const (
	// Fail the conversion if the result is not an integer.
	SizeRoundingBehavior_FAIL SizeRoundingBehavior = "FAIL"
	// If the result is not an integer, round it to the closest integer less than the result.
	SizeRoundingBehavior_FLOOR SizeRoundingBehavior = "FLOOR"
	// Don't round.
	//
	// Return even if the result is a fraction.
	SizeRoundingBehavior_NONE SizeRoundingBehavior = "NONE"
)

// Testing utilities for cdk8s applications.
type Testing interface {
}

// The jsii proxy struct for Testing
type jsiiProxy_Testing struct {
	_ byte // padding
}

// Returns an app for testing with the following properties: - Output directory is a temp dir.
func Testing_App(props *AppProps) App {
	_init_.Initialize()

	var returns App

	_jsii_.StaticInvoke(
		"cdk8s.Testing",
		"app",
		[]interface{}{props},
		&returns,
	)

	return returns
}

// Returns: a Chart that can be used for tests.
func Testing_Chart() Chart {
	_init_.Initialize()

	var returns Chart

	_jsii_.StaticInvoke(
		"cdk8s.Testing",
		"chart",
		nil, // no parameters
		&returns,
	)

	return returns
}

// Returns the Kubernetes manifest synthesized from this chart.
func Testing_Synth(chart Chart) *[]interface{} {
	_init_.Initialize()

	var returns *[]interface{}

	_jsii_.StaticInvoke(
		"cdk8s.Testing",
		"synth",
		[]interface{}{chart},
		&returns,
	)

	return returns
}

// Options for how to convert time to a different unit.
type TimeConversionOptions struct {
	// If `true`, conversions into a larger time unit (e.g. `Seconds` to `Minutes`) will fail if the result is not an integer.
	Integral *bool `json:"integral" yaml:"integral"`
}

// YAML utilities.
type Yaml interface {
}

// The jsii proxy struct for Yaml
type jsiiProxy_Yaml struct {
	_ byte // padding
}

// Deprecated: use `stringify(doc[, doc, ...])`
func Yaml_FormatObjects(docs *[]interface{}) *string {
	_init_.Initialize()

	var returns *string

	_jsii_.StaticInvoke(
		"cdk8s.Yaml",
		"formatObjects",
		[]interface{}{docs},
		&returns,
	)

	return returns
}

// Downloads a set of YAML documents (k8s manifest for example) from a URL or a file and returns them as javascript objects.
//
// Empty documents are filtered out.
//
// Returns: an array of objects, each represents a document inside the YAML.
func Yaml_Load(urlOrFile *string) *[]interface{} {
	_init_.Initialize()

	var returns *[]interface{}

	_jsii_.StaticInvoke(
		"cdk8s.Yaml",
		"load",
		[]interface{}{urlOrFile},
		&returns,
	)

	return returns
}

// Saves a set of objects as a multi-document YAML file.
func Yaml_Save(filePath *string, docs *[]interface{}) {
	_init_.Initialize()

	_jsii_.StaticInvokeVoid(
		"cdk8s.Yaml",
		"save",
		[]interface{}{filePath, docs},
	)
}

// Stringify a document (or multiple documents) into YAML.
//
// We convert undefined values to null, but ignore any documents that are
// undefined.
//
// Returns: a YAML string. Multiple docs are separated by `---`.
func Yaml_Stringify(docs ...interface{}) *string {
	_init_.Initialize()

	args := []interface{}{}
	for _, a := range docs {
		args = append(args, a)
	}

	var returns *string

	_jsii_.StaticInvoke(
		"cdk8s.Yaml",
		"stringify",
		args,
		&returns,
	)

	return returns
}

// Saves a set of YAML documents into a temp file (in /tmp).
//
// Returns: the path to the temporary file.
func Yaml_Tmp(docs *[]interface{}) *string {
	_init_.Initialize()

	var returns *string

	_jsii_.StaticInvoke(
		"cdk8s.Yaml",
		"tmp",
		[]interface{}{docs},
		&returns,
	)

	return returns
}

// The method to divide YAML output into files.
type YamlOutputType string

const (
	// All resources are output into a single YAML file.
	YamlOutputType_FILE_PER_APP YamlOutputType = "FILE_PER_APP"
	// Resources are split into seperate files by chart.
	YamlOutputType_FILE_PER_CHART YamlOutputType = "FILE_PER_CHART"
	// Each resource is output to its own file.
	YamlOutputType_FILE_PER_RESOURCE YamlOutputType = "FILE_PER_RESOURCE"
	// Each chart in its own folder and each resource in its own file.
	YamlOutputType_FOLDER_PER_CHART_FILE_PER_RESOURCE YamlOutputType = "FOLDER_PER_CHART_FILE_PER_RESOURCE"
)

