package cdk8s


type ChartProps struct {
	// The autogenerated resource name by default is suffixed with a stable hash of the construct path.
	//
	// Setting this property to true drops the hash suffix.
	// Default: false.
	//
	DisableResourceNameHashes *bool `field:"optional" json:"disableResourceNameHashes" yaml:"disableResourceNameHashes"`
	// Labels to apply to all resources in this chart.
	// Default: - no common labels.
	//
	Labels *map[string]*string `field:"optional" json:"labels" yaml:"labels"`
	// The default namespace for all objects defined in this chart (directly or indirectly).
	//
	// This namespace will only apply to objects that don't have a
	// `namespace` explicitly defined for them.
	// Default: - no namespace is synthesized (usually this implies "default").
	//
	Namespace *string `field:"optional" json:"namespace" yaml:"namespace"`
}

