package cdk8s

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2/jsii"
)

// Resolves union types that allow using either number or string (as generated by the CLI).
//
// E.g IntOrString, Quantity, ...
type NumberStringUnionResolver interface {
	IResolver
	// This function is invoked on every property during cdk8s synthesis.
	//
	// To replace a value, implementations must invoke `context.replaceValue`.
	Resolve(context ResolutionContext)
}

// The jsii proxy struct for NumberStringUnionResolver
type jsiiProxy_NumberStringUnionResolver struct {
	jsiiProxy_IResolver
}

func NewNumberStringUnionResolver() NumberStringUnionResolver {
	_init_.Initialize()

	j := jsiiProxy_NumberStringUnionResolver{}

	_jsii_.Create(
		"cdk8s.NumberStringUnionResolver",
		nil, // no parameters
		&j,
	)

	return &j
}

func NewNumberStringUnionResolver_Override(n NumberStringUnionResolver) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk8s.NumberStringUnionResolver",
		nil, // no parameters
		n,
	)
}

func (n *jsiiProxy_NumberStringUnionResolver) Resolve(context ResolutionContext) {
	if err := n.validateResolveParameters(context); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		n,
		"resolve",
		[]interface{}{context},
	)
}

